name: Daily Model Finetuning

on:
  schedule:
    # Menjalankan setiap hari jam 1 pagi UTC (sekitar jam 8 pagi WIB)
    - cron: '0 1 * * *'
  workflow_dispatch: # Memungkinkan untuk menjalankan manual

jobs:
  finetune:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Pastikan versi python sesuai

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run finetuning script
        run: python finetuning.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add model_finetuned_btc_2025.h5 scaler_finetuned.save
          # Hanya commit jika ada perubahan pada file
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Chore: Auto-update prediction model and scaler" && git push)
