name: Daily Model Finetuning

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  finetune:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run finetuning script
        run: python finetuning.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add model_finetuned_btc_2025.h5 scaler_finetuned.save
          # Cek apakah ada perubahan sebelum commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "🤖 Chore: Auto-update prediction model"
            git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:main
          fi
